from .shared import *
from .selection import _dedupe_preserve_order
from .pmf_landscape import _pmf_temperature_from_frame
from ...analysis.pmf_vectorize import parse_family as _pmf_parse_family


def _umap_source_mode(value) -> str:
    """Normalize UMAP input-source preset."""
    v = str(value or UMAP_SOURCE_BASIC).strip().lower()
    aliases = {
        "native": UMAP_SOURCE_BASIC,
        "basic_native": UMAP_SOURCE_BASIC,
        "feature": UMAP_SOURCE_BASIC,
        "features": UMAP_SOURCE_BASIC,
        "basin": UMAP_SOURCE_THERMO,
        "basin_geometry": UMAP_SOURCE_THERMO,
        "corrected": UMAP_SOURCE_THERMO,
        "thermo": UMAP_SOURCE_THERMO,
        "pmf": UMAP_SOURCE_PMF,
        "pmfs": UMAP_SOURCE_PMF,
        "shape": UMAP_SOURCE_PMF,
        "pmf_vector": UMAP_SOURCE_PMF,
        "pmf_vectors": UMAP_SOURCE_PMF,
        "seq": UMAP_SOURCE_SEQUENCE,
        "sequence": UMAP_SOURCE_SEQUENCE,
        "letters": UMAP_SOURCE_SEQUENCE,
        "letter": UMAP_SOURCE_SEQUENCE,
        "aminoacid": UMAP_SOURCE_SEQUENCE,
        "amino_acid": UMAP_SOURCE_SEQUENCE,
        "aa": UMAP_SOURCE_SEQUENCE,
    }
    valid = {UMAP_SOURCE_BASIC, UMAP_SOURCE_THERMO, UMAP_SOURCE_PMF, UMAP_SOURCE_SEQUENCE}
    return aliases.get(v, v if v in valid else UMAP_SOURCE_BASIC)


def _is_sequence_feature_col(col: str) -> bool:
    s = str(col)
    return (
        s.startswith("seq_")
        or s == "sequence"
        or s in {"L", "KD_mean", "KD_std", "KD_min", "KD_max", "KD_Nterm", "KD_Cterm"}
    )


def _sequence_umap_feature_cols(df: pd.DataFrame, raw_cols: Optional[Sequence[str]] = None) -> List[str]:
    """Columns for sequence/letter-space UMAP input.

    Prefer normalized, interpretable descriptors generated by batch_ana. Raw
    residue counts are intentionally excluded from the embedding by default
    because they mostly duplicate sequence length; counts remain available for
    ML outside this tab.
    """
    if not isinstance(df, pd.DataFrame) or df.empty:
        return []
    raw = list(raw_cols) if raw_cols is not None else [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    raw_set = {str(c) for c in raw}
    aa_order = "ACDEFGHIKLMNPQRSTVWY"
    preferred: List[str] = []

    explicit = [
        "seq_length",
        "seq_known_frac",
        "seq_unknown_frac",
        "seq_net_charge_pH7_approx",
        "seq_abs_net_charge_pH7_approx",
        "seq_charge_density_pH7_approx",
        "seq_abs_charge_density_pH7_approx",
        "seq_kd_mean",
        "seq_kd_std",
        "seq_kd_min",
        "seq_kd_max",
        "seq_kd_range",
        "seq_kd_nterm",
        "seq_kd_cterm",
        "seq_composition_entropy_bits",
        "seq_composition_entropy_norm20",
        "seq_unique_aa_count",
        "seq_unique_aa_frac20",
        "seq_max_run_len",
        "seq_max_run_frac",
    ]
    preferred.extend([c for c in explicit if c in raw_set])
    preferred.extend([f"seq_aa_{aa}_frac" for aa in aa_order if f"seq_aa_{aa}_frac" in raw_set])
    for prefix in ("seq_frac_", "seq_nterm_", "seq_cterm_"):
        preferred.extend(sorted([c for c in raw_set if c.startswith(prefix)]))

    # Backward-compatible minimal sequence columns from older batch_ana outputs.
    if not preferred:
        fallback = ["L", "KD_mean", "KD_std", "KD_min", "KD_max", "KD_Nterm", "KD_Cterm"]
        preferred.extend([c for c in fallback if c in raw_set])

    # Deduplicate while preserving order.
    out: List[str] = []
    seen = set()
    for c in preferred:
        if c in seen or c not in df.columns:
            continue
        if not pd.api.types.is_numeric_dtype(df[c]):
            continue
        out.append(c)
        seen.add(c)
    return out


def _wide_feature_stat(col: object) -> Optional[str]:
    c = str(col)
    if "__" not in c:
        return None
    return c.split("__", 1)[1]


def _is_pmf_core_wide_col(col: object) -> bool:
    return _wide_feature_stat(col) in set(PMF_CORE_FEATURES)


def _is_pmf_physical_annotation_wide_col(col: object) -> bool:
    return _wide_feature_stat(col) in set(PMF_PHYSICAL_ANNOTATIONS)


def _pmf_core_wide_cols(df: pd.DataFrame, cols: Optional[List[str]] = None) -> List[str]:
    if not isinstance(df, pd.DataFrame) or df.empty:
        return []
    base_cols = cols if cols is not None else list(df.columns)
    return [
        c for c in base_cols
        if c in df.columns
        and c != "variant"
        and pd.api.types.is_numeric_dtype(df[c])
        and _is_pmf_core_wide_col(c)
    ]


def _transform_wide_pmf_core(df_num: pd.DataFrame) -> Tuple[pd.DataFrame, str]:
    """Apply PMF intrinsic transforms to wide metric__feature columns."""
    if not isinstance(df_num, pd.DataFrame) or df_num.empty:
        return pd.DataFrame(index=getattr(df_num, "index", None)), ""
    tmp = df_num.copy()
    rename: Dict[str, str] = {}
    rev: Dict[str, str] = {}
    rules: Dict[str, str] = {}
    for i, c in enumerate(tmp.columns.astype(str)):
        stat = _wide_feature_stat(c) or c
        tmp_name = f"{stat}__wide{i}"
        rename[c] = tmp_name
        rev[tmp_name] = c
        rules[tmp_name] = PMF_TRANSFORM_RULES.get(stat, "zscore")
    tmp = tmp.rename(columns=rename)
    Xt, meta = transform_features(tmp, rules, scaler_scope="current_selection")
    Xt = Xt.rename(columns=rev)
    used = sorted({str(v) for v in meta.get("columns", {}).values() if v != "none"})
    note = "thermodynamic PMF-core transforms applied"
    if used:
        note += f" ({', '.join(used)})"
    return Xt, note


from ...data.variant_pmf import normalize_pmf_curve_columns as _normalize_pmf_curve_columns


def _coerce_pmf_metric_selection(selected: Optional[Sequence[str]], available: Sequence[str]) -> List[str]:
    avail = [str(m) for m in available if m is not None]
    if not avail:
        return []
    if selected:
        sel_set = {str(m) for m in selected if m is not None}
        kept = [m for m in avail if m in sel_set]
        if kept:
            return kept
    return avail


def _prepare_feature_design_matrix(
    feats_df: pd.DataFrame,
    source_mode: str,
    *,
    selected_metrics: Optional[Sequence[str]] = None,
) -> Tuple[np.ndarray, List[str], pd.DataFrame, str]:
    """Build scalar-feature design matrix for UMAP source modes basic/thermodynamic/sequence."""
    df = feats_df.copy() if isinstance(feats_df, pd.DataFrame) else pd.DataFrame()
    if df.empty:
        return np.zeros((0, 0)), [], pd.DataFrame(), "No feature table available."
    if "variant" not in df.columns:
        df = df.copy()
        df.insert(0, "variant", np.arange(len(df)).astype(str))
    raw = [c for c in df.columns if c != "variant" and pd.api.types.is_numeric_dtype(df[c])]
    raw = filter_numeric_columns(raw)
    if not raw:
        return np.zeros((0, 0)), [], pd.DataFrame(), "No numeric feature columns available."
    notes: List[str] = []
    mode = _umap_source_mode(source_mode)
    if mode == UMAP_SOURCE_SEQUENCE:
        cols = _sequence_umap_feature_cols(df, raw)
        if not cols:
            return (
                np.zeros((0, 0)),
                [],
                pd.DataFrame(),
                "No sequence/letter-space columns found. Re-run batch_ana so features contains seq_* descriptors.",
            )
        num_df = df[cols].apply(pd.to_numeric, errors="coerce")
        notes.append(f"source=sequence/letter-space descriptors; {len(cols)} interpretable sequence feature(s)")
    elif mode == UMAP_SOURCE_THERMO:
        core = _pmf_core_wide_cols(df, raw)
        if core:
            selected = None
            if selected_metrics:
                sel = {str(m) for m in selected_metrics}
                selected = [c for c in core if str(c).split("__", 1)[0] in sel]
            cols = selected if selected else core
            num_df = df[cols].apply(pd.to_numeric, errors="coerce")
            num_df, transform_note = _transform_wide_pmf_core(num_df)
            notes.append("source=thermodynamic/basin-corrected")
            if transform_note:
                notes.append(transform_note)
        else:
            cols = raw
            num_df = df[cols].apply(pd.to_numeric, errors="coerce")
            notes.append("source=thermodynamic requested, but no PMF-core columns found; fell back to basic/native features")
    else:
        # Keep sequence/letter-space descriptors isolated in their own source
        # mode. Once io.py merges seq_* columns into ctx.features, blindly using
        # all numeric columns here would contaminate the native thermodynamic
        # scalar space with sequence composition variables. Physical PMF
        # annotations are also excluded here because they mix nm, degrees, and
        # other native coordinate units across observable blocks.
        cols = [c for c in raw if not _is_sequence_feature_col(c) and not _is_pmf_physical_annotation_wide_col(c)]
        if not cols:
            return (
                np.zeros((0, 0)),
                [],
                pd.DataFrame(),
                "No basic/native numeric columns remain after excluding sequence descriptors and mixed-unit PMF annotations.",
            )
        else:
            notes.append("source=basic/native scalar features; sequence descriptors and mixed-unit PMF annotations excluded")
        num_df = df[cols].apply(pd.to_numeric, errors="coerce")
    num_df = num_df.replace([np.inf, -np.inf], np.nan)
    finite_counts = num_df.notna().sum(axis=0)
    keep_cols = finite_counts[finite_counts >= 3].index.tolist()
    if len(keep_cols) < 2:
        keep_cols = finite_counts[finite_counts >= 2].index.tolist()
    if len(keep_cols) < 2:
        return np.zeros((0, 0)), [], pd.DataFrame(), "Not enough numeric columns with finite support."
    num_df = num_df[keep_cols]
    finite_var = num_df.var(axis=0, skipna=True)
    keep_cols = [c for c in keep_cols if pd.notna(finite_var.get(c)) and float(finite_var.get(c)) > 0.0]
    if len(keep_cols) < 2:
        return np.zeros((0, 0)), [], pd.DataFrame(), "Feature columns are constant or mostly missing."
    num_df = num_df[keep_cols]
    row_support = num_df.notna().sum(axis=1)
    keep_rows = row_support >= min(2, len(keep_cols))
    if not bool(np.any(keep_rows)):
        return np.zeros((0, 0)), [], pd.DataFrame(), "No rows with enough finite feature values."
    num_df = num_df.loc[keep_rows].copy()
    med = num_df.median(axis=0, skipna=True).fillna(0.0)
    num_df = num_df.fillna(med).fillna(0.0)
    if num_df.shape[0] < 3:
        return np.zeros((0, 0)), [], pd.DataFrame(), "Feature-based UMAP needs at least 3 usable variants."
    X = num_df.to_numpy(dtype=float)
    meta = pd.DataFrame({"variant": df.loc[num_df.index, "variant"].astype(str).tolist()})
    return X, list(num_df.columns.astype(str)), meta, "; ".join(notes)

def _build_pmf_shape_matrix_for_umap(
    pmf_df: pd.DataFrame,
    selected_metrics: Optional[Sequence[str]],
    use_repr: str = "P",
) -> Tuple[np.ndarray, List[str], pd.DataFrame, str]:
    """Build sqrt(P_mass) PMF-shape matrix using PCA tab's union+mean policy."""
    if not isinstance(pmf_df, pd.DataFrame) or pmf_df.empty:
        return np.zeros((0, 0)), [], pd.DataFrame(), "No PMF table available."
    if not {"variant", "metric", "x"}.issubset(set(pmf_df.columns)):
        return np.zeros((0, 0)), [], pd.DataFrame(), "PMF table lacks variant/metric/x columns."
    d = _normalize_pmf_curve_columns(pmf_df)
    available = sorted(d["metric"].dropna().astype(str).unique().tolist(), key=str.lower)
    metrics = _coerce_pmf_metric_selection(selected_metrics, available)
    if not metrics:
        return np.zeros((0, 0)), [], pd.DataFrame(), "No PMF metrics selected/available."
    d = d[d["metric"].astype(str).isin(metrics)].copy()
    if d.empty:
        return np.zeros((0, 0)), [], pd.DataFrame(), "Selected PMF metrics are absent."
    if "P" not in d.columns and "F_kJ_mol" not in d.columns:
        return np.zeros((0, 0)), [], pd.DataFrame(), "PMF table has no usable P or F_kJ_mol/free-energy alias."
    use_repr_s = str(use_repr or "P")
    repr_mode = "P" if use_repr_s in ("P", "log_P") and "P" in d.columns else "F"
    if repr_mode == "F" and "F_kJ_mol" not in d.columns and "P" in d.columns:
        repr_mode = "P"
    T_eff = _pmf_temperature_from_frame(d)
    X, colnames, meta, grids = build_pmf_design_matrix(
        d,
        metrics,
        use_repr=repr_mode,
        energy_units="kJ/mol",
        T_K=T_eff,
        max_bins_per_metric=192,
        variant_policy="union_mean",
        missing_impute="mean",
        dirichlet_alpha=0.0,
    )
    if X.size == 0 or not colnames or meta.empty:
        return np.zeros((0, 0)), [], pd.DataFrame(), "Could not construct PMF-shape design matrix."
    if use_repr_s == "log_P":
        X = np.log(np.clip(X, 1e-6, None))
        repr_label = "log(P)"
    else:
        X = np.sqrt(np.clip(X, 0.0, None))
        repr_label = "sqrt(P_mass)"
    families = [_pmf_parse_family(c) for c in colnames]
    fam_counts = pd.Series(families).value_counts().to_dict()
    weights = np.array([1.0 / np.sqrt(max(1, int(fam_counts.get(f, 1)))) for f in families], dtype=float)
    X = X * weights[None, :]
    note = (
        f"source=PMFs themselves; {repr_label} vectors; "
        f"{len(metrics)} selected PMF metric block(s), {len(colnames)} bins/features; "
        f"variant_policy=union_mean; metric blocks scaled by 1/sqrt(n_bins); T={T_eff:g} K"
    )
    return X, colnames, meta, note

def _pmf_matrix_for_umap(
    pmf_df: pd.DataFrame,
    metrics: List[str],
    use_repr: str = "P",
    T: float = 300.0,
    *,
    x_round_decimals: int = 4,
    max_bins_per_metric: int = 256,
    normalize_by_integral: bool = True,
) -> Tuple[np.ndarray, List[str], pd.DataFrame]:
    """
    Build a PMF design matrix for embedding.

    Scientific notes / why this exists
    -------------------------------
    PMF tables often have:
      1) slight floating point jitter in x bins across variants (creating many near-duplicate columns),
      2) different x coverage per variant (missing bins),
      3) different bin widths (dx) across metrics, and
      4) multiple metrics concatenated where "more bins" can dominate.

    This builder:
      - rounds x to `x_round_decimals` to collapse float jitter,
      - interpolates each variant's curve onto a per-metric common grid,
      - normalizes each variant distribution by \\int p(x) dx when possible (dx estimated from the grid),
      - returns *intersection* of variants across metrics (same behavior as before).

    Returns
    -------
    X        : (n_variants, n_features) matrix, features are concatenated metric bins
    colnames : names like "<metric>|x=<bin>"
    meta     : DataFrame with column "variant" aligned to rows of X
    """
    if pmf_df.empty or not metrics:
        return np.zeros((0, 0)), [], pd.DataFrame()

    if "variant" not in pmf_df.columns or "metric" not in pmf_df.columns or "x" not in pmf_df.columns:
        return np.zeros((0, 0)), [], pd.DataFrame()

    # Use kT for converting free energy to probability if needed
    kT = max(R_GAS * float(T), 1e-12)

    def _median_dx(xg: np.ndarray) -> float:
        xg = np.asarray(xg, dtype=float)
        xg = xg[np.isfinite(xg)]
        if xg.size < 2:
            return 1.0
        d = np.diff(np.unique(xg))
        if d.size == 0:
            return 1.0
        return float(np.median(d))

    mats: List[pd.DataFrame] = []
    meta_variants_common: Optional[set] = None

    used_metrics: List[str] = []
    out_colnames: List[str] = []

    for m in list(metrics):
        sub = pmf_df[pmf_df["metric"].astype(str) == str(m)].copy()
        if sub.empty:
            continue

        sub["variant"] = sub["variant"].astype(str)
        sub["x"] = pd.to_numeric(sub["x"], errors="coerce")
        sub = sub.dropna(subset=["x"])
        if sub.empty:
            continue

        # Collapse float jitter in x bins
        sub["x_r"] = sub["x"].round(int(x_round_decimals))

        use_P = (use_repr == "P") and ("P" in sub.columns)

        if use_P:
            sub["val"] = pd.to_numeric(sub["P"], errors="coerce").clip(lower=0.0)
        else:
            if "F_kJ_mol" in sub.columns:
                F = pd.to_numeric(sub["F_kJ_mol"], errors="coerce")
                # Per-variant reference shift to prevent underflow, then exponentiate
                F = F - F.groupby(sub["variant"]).transform("min")
                sub["val"] = np.exp(-np.clip(F.to_numpy(dtype=float), 0.0, 700.0) / kT)
            elif "P" in sub.columns:
                sub["val"] = pd.to_numeric(sub["P"], errors="coerce").clip(lower=0.0)
            else:
                continue

        sub = sub.dropna(subset=["val"])
        if sub.empty:
            continue

        # Build a per-metric common x-grid (rounded)
        x_grid = np.unique(sub["x_r"].to_numpy(dtype=float))
        x_grid = x_grid[np.isfinite(x_grid)]
        if x_grid.size < 2:
            continue
        x_grid.sort()

        # Optional dimension control (prevents a single metric with tiny dx from exploding feature count)
        if int(max_bins_per_metric) > 0 and x_grid.size > int(max_bins_per_metric):
            x_grid = np.linspace(float(x_grid.min()), float(x_grid.max()), int(max_bins_per_metric), dtype=float)

        dx = _median_dx(x_grid)

        # Interpolate every variant to the common grid
        rows: List[np.ndarray] = []
        variants_here: List[str] = []

        for v, g in sub.groupby("variant", sort=False):
            gx = g[["x_r", "val"]].dropna()
            if gx.empty:
                continue

            # Average duplicates at the same rounded x
            gx = gx.groupby("x_r", as_index=False)["val"].mean().sort_values("x_r")
            xv = gx["x_r"].to_numpy(dtype=float)
            pv = gx["val"].to_numpy(dtype=float)

            if xv.size < 2:
                continue

            # Ensure finite and non-negative
            pv = np.clip(np.nan_to_num(pv, nan=0.0, posinf=0.0, neginf=0.0), 0.0, None)

            # Interpolate onto the global grid
            p_i = np.interp(x_grid, xv, pv, left=0.0, right=0.0)

            if normalize_by_integral:
                Z = float(np.sum(p_i) * dx)
                if np.isfinite(Z) and Z > 0:
                    p_i = p_i / Z

            rows.append(p_i.astype(float))
            variants_here.append(str(v))

        if not rows:
            continue

        piv = pd.DataFrame(np.vstack(rows), index=variants_here, columns=x_grid.astype(float))
        piv = piv.sort_index(axis=0).sort_index(axis=1)

        vset = set(piv.index.tolist())
        meta_variants_common = vset if meta_variants_common is None else (meta_variants_common & vset)
        mats.append(piv)
        used_metrics.append(str(m))

    if not mats or not meta_variants_common:
        return np.zeros((0, 0)), [], pd.DataFrame()

    common = sorted(meta_variants_common)
    aligned = [m.loc[common, :] for m in mats]
    X = np.concatenate([a.to_numpy(dtype=float) for a in aligned], axis=1)

    for m, a in zip(used_metrics, aligned):
        out_colnames.extend([f"{m}|x={x:g}" for x in a.columns.to_numpy(dtype=float)])

    meta = pd.DataFrame({"variant": common})
    return X, out_colnames, meta
